{"uid":"526953c3fd85618","name":"Check App build and running & Check app elements exist","fullName":"Check App build and running & Check app elements exist","historyId":"c1e712afb221157f3d586affd994cf6a","time":{"start":1698629613229,"stop":1698629614212,"duration":983},"status":"broken","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_04 (http://localhost:3001/main.js:69:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:419:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:440:15)\n    at <unknown> (http://localhost:3001/main.js:552:47)\n    at webpack/sharing/consume/default/react/react?aabd (http://localhost:3001/main.js:606:72)\n    at <unknown> (http://localhost:3001/main.js:671:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:654:36)\n    at <unknown> (http://localhost:3001/main.js:207:40)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":true,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_04 (http://localhost:3001/main.js:69:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:419:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:440:15)\n    at <unknown> (http://localhost:3001/main.js:552:47)\n    at webpack/sharing/consume/default/react/react?aabd (http://localhost:3001/main.js:606:72)\n    at <unknown> (http://localhost:3001/main.js:671:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:654:36)\n    at <unknown> (http://localhost:3001/main.js:207:40)","steps":[{"name":"\"before each\" hook","time":{"start":1698629613229,"stop":1698629614212,"duration":983},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_04 (http://localhost:3001/main.js:69:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:419:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:440:15)\n    at <unknown> (http://localhost:3001/main.js:552:47)\n    at webpack/sharing/consume/default/react/react?aabd (http://localhost:3001/main.js:606:72)\n    at <unknown> (http://localhost:3001/main.js:671:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:654:36)\n    at <unknown> (http://localhost:3001/main.js:207:40)","steps":[{"name":"visit http://localhost:3001","time":{"start":1698629613311,"stop":1698629614212,"duration":901},"status":"failed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"uncaught exception ScriptExternalLoadError: Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04","time":{"start":1698629614212,"stop":1698629614212,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.runAllComprehensiveDemoReact18Tests.cy.ts"},{"name":"parentSuite","value":"Comprehencive Demo React 18"},{"name":"suite","value":"Check is Comprehensive Demo App1 working and have elements"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"585689883c7dac5f","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1698629611312,"stop":1698629613210,"duration":1898}},{"uid":"dfcb487fe3a25974","status":"broken","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1698629548090,"stop":1698629548943,"duration":853}},{"uid":"e524b960c397a40c","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3004/remoteEntry.js)\nwhile loading \"./loadApp\" from webpack/container/reference/app_04\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1698629546586,"stop":1698629548050,"duration":1464}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":7,"unknown":0,"total":11},"items":[{"uid":"aef0269cfe2bcd6c","reportUrl":"https://module-federation.github.io/module-federation-examples/1444//#testresult/aef0269cfe2bcd6c","status":"broken","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1698618070829,"stop":1698618071649,"duration":820}},{"uid":"94610e51755cadac","reportUrl":"https://module-federation.github.io/module-federation-examples/1443//#testresult/94610e51755cadac","status":"broken","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1698616681381,"stop":1698616682211,"duration":830}},{"uid":"71426ec6e0e295c1","reportUrl":"https://module-federation.github.io/module-federation-examples/1442//#testresult/71426ec6e0e295c1","status":"passed","time":{"start":1698614018441,"stop":1698614018811,"duration":370}},{"uid":"c32c7cc372728a21","reportUrl":"https://module-federation.github.io/module-federation-examples/1426//#testresult/c32c7cc372728a21","status":"passed","time":{"start":1698562404428,"stop":1698562404851,"duration":423}},{"uid":"3a380fcd803f4dbb","reportUrl":"https://module-federation.github.io/module-federation-examples/1374//#testresult/3a380fcd803f4dbb","status":"broken","statusDetails":"`cy.visit()` failed trying to load:\n\nhttp://localhost:3002/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:3002\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","time":{"start":1698528976054,"stop":1698528976974,"duration":920}},{"uid":"830ee6a2369c543","reportUrl":"https://module-federation.github.io/module-federation-examples/897//#testresult/830ee6a2369c543","status":"passed","time":{"start":1682421368824,"stop":1682421369010,"duration":186}},{"uid":"4678cb160d6a4708","reportUrl":"https://module-federation.github.io/module-federation-examples/879//#testresult/4678cb160d6a4708","status":"passed","time":{"start":1682325254075,"stop":1682325254481,"duration":406}},{"uid":"9b44c9c17b57b29e","reportUrl":"https://module-federation.github.io/module-federation-examples/848//#testresult/9b44c9c17b57b29e","status":"passed","time":{"start":1682212105488,"stop":1682212105779,"duration":291}},{"uid":"5e03ea780440390","reportUrl":"https://module-federation.github.io/module-federation-examples/843//#testresult/5e03ea780440390","status":"passed","time":{"start":1682212105488,"stop":1682212105488,"duration":0}},{"uid":"a7939a9c72394975","reportUrl":"https://module-federation.github.io/module-federation-examples/831//#testresult/a7939a9c72394975","status":"passed","time":{"start":1682212105488,"stop":1682212105779,"duration":291}}]},"tags":[]},"source":"526953c3fd85618.json","parameterValues":[]}